#!/bin/bash
# myapp daemon
# chkconfig: 345 20 80
# description: myapp daemon
# processname: myapp

HOST=0.0.0.0
PORT=9031
WORKERS=1

PROJECT=product-detection
DAEMON_PATH="/zserver/python-projects/$PROJECT"
CONF_FILE="src.main:app"
LOG_FILE=/zserver/tmp/$PROJECT/$PROJECT.log
mkdir -p /zserver/tmp/$PROJECT/

if [ "x$2" != "x" ]; then
APP_PROF="$2"
else
APP_PROF="staging"
fi

DAEMON="env ENV=$APP_PROF /zserver/python3/env-$PROJECT/bin/uvicorn"
DAEMONOPTS="$CONF_FILE --host $HOST --port $PORT --workers $WORKERS"

NAME="$PROJECT uvicorn src.main:app"
DESC="$PROJECT uvicorn src.main:app"
PIDFILE=/zserver/tmp/$PROJECT/$PROJECT.pid


case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	#PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
	$DAEMON $DAEMONOPTS > $LOG_FILE 2>&1 &
	PID=`echo -n $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME\n"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $(ps -o pid= --ppid $PID)
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	/bin/bash $0 stop $APP_PROF
  	/bin/bash $0 start $APP_PROF
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
